name: Update Main Release

on:
  repository_dispatch:
    types: 'main-release'

jobs:
  main-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Update Main Release
      run: ./gradlew updateMainRelease --release="${{ github.event.client_payload.version }}"
    - name: Create Pull Request
      run: ./gradlew createPullRequestMainRelease
      env:
        ZAPBOT_TOKEN: ${{ secrets.ZAPBOT_TOKEN }}
